
services:
  - type: web
    name: apex-paragon-ai
    env: python
    plan: starter
    buildCommand: "./install.sh"
    startCommand: "./start.sh"
    envVars:
      - key: GOLD_API_KEY
        sync: false
    autoDeploy: true
